# Generated by Django 4.2.1 on 2023-05-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_name", models.CharField(max_length=50)),
                ("target_area", models.CharField(max_length=50)),
                ("difficulty", models.CharField(max_length=20)),
                ("date_added", models.DateTimeField(verbose_name="Date Added")),
            ],
        ),
    ]
